name: subpackage_2
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  subpackage_3:
    path: ../subpackage_3

dev_dependencies:
  pedantic: ^1.9.0
